{
  "type": "record",
  "name": "MarketType",
  "namespace": "sportsbook.avro.outbound.enum",
  "fields": [
    {
      "name": "origin",
      "type": {
        "type": "record",
        "name": "Origin",
        "fields": [
          {
            "name": "stream",
            "type": "string"
          },
          {
            "name": "type",
            "type": {
              "type": "enum",
              "name": "OriginTypeEnum",
              "symbols": [
                "sport",
                "league",
                "team",
                "lineEntity",
                "gamePeriod",
                "marketType",
                "market",
                "country"
              ]
            }
          },
          {
            "name": "version",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "referentialConstraint",
      "type": {
        "type": "map",
        "values": "string"
      }
    },
    {
      "name": "value",
      "type": "string"
    }
  ]
}